# Generated by Django 4.1 on 2022-08-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('duration', models.FloatField()),
                ('starttime', models.DateField()),
                ('passwords', models.CharField(max_length=250)),
            ],
        ),
    ]
